#if TOOLS
using Godot;
using System;
using System.Text;

namespace DataForge
{
    /// <summary>
    /// DataForge 增强版主窗口 - 代码生成
    /// 
    /// 职责：
    /// - C# 代码生成
    /// - 值格式化（字符串、数字、枚举、子对象）
    /// - 代码模板应用
    /// </summary>
    public partial class DataForgeWindowEnhanced
    {
        #region === 代码生成 ===

        private void GenerateCode()
        {
            SaveToJson();

            var sb = new StringBuilder();

            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("// -----------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//     此代码由 DataForge Enhanced 自动生成");
            sb.AppendLine($"//     源文件: {_currentTemplate.SavePath}");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//     ⚠️ 请勿手动修改此文件!");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// -----------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine($"/// <summary>");
            sb.AppendLine($"/// {_currentTemplate.DisplayName}（自动生成）");
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"public static class {_currentTemplate.ClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static readonly Dictionary<string, Dictionary<string, object>> Configs = new()");
            sb.AppendLine("    {");

            foreach (var row in _tableData)
            {
                if (!row.TryGetValue("RowID", out var rowId) || string.IsNullOrWhiteSpace(rowId))
                    continue;

                sb.AppendLine($"        [\"{rowId}\"] = new()");
                sb.AppendLine("        {");

                foreach (var col in _columns)
                {
                    if (col.Key == "RowID") continue;
                    if (!row.TryGetValue(col.Key, out var val) || string.IsNullOrWhiteSpace(val))
                        continue;

                    string formattedValue = FormatValueForCode(col, val);
                    if (formattedValue != null)
                    {
                        sb.AppendLine($"            {{ DataKey.{col.Key}, {formattedValue} }},");
                    }
                }

                sb.AppendLine("        },");
                sb.AppendLine();
            }

            sb.AppendLine("    };");
            sb.AppendLine("}");

            try
            {
                EnsureDirectoryExists(_currentTemplate.OutputPath);
                string fullPath = ProjectSettings.GlobalizePath(_currentTemplate.OutputPath);
                System.IO.File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);

                UpdateStatus($"✅ 代码已生成: {_currentTemplate.OutputPath}");
                EditorInterface.Singleton.GetResourceFilesystem().Scan();
            }
            catch (Exception e)
            {
                GD.PrintErr($"[DataForge] 代码生成失败: {e}");
                UpdateStatus($"❌ 代码生成失败: {e.Message}");
            }
        }

        private string? FormatValueForCode(ColumnDefinition col, string val)
        {
            if (string.IsNullOrWhiteSpace(val)) return null;
            val = val.Trim();

            if (!string.IsNullOrEmpty(col.CodeTemplate))
                return string.Format(col.CodeTemplate, val);

            if (col.EditorType == FieldEditorType.Enum && !string.IsNullOrEmpty(col.EnumTypeName))
                return $"{col.EnumTypeName}.{val}";

            if (col.EditorType == FieldEditorType.SubObject && !string.IsNullOrEmpty(col.SubObjectTypeName))
                return FormatSubObjectForCode(col.SubObjectTypeName, val);

            return col.FieldType switch
            {
                FieldType.Bool => val.ToLower(),
                FieldType.Float => val.Contains(".") ? $"{val}f" : $"{val}f",
                FieldType.Int => val,
                _ => $"\"{val}\""
            };
        }

        private string FormatSubObjectForCode(string typeName, string jsonVal)
        {
            return $"/* TODO: Parse {typeName} */";
        }

        #endregion
    }
}
#endif
